version: "3.3"
services:
  web:
    build:
      context: ./.build
      dockerfile: Dockerfile.Web
    image: t3easy/typo3:web

  typo3:
    build:
      context: ./.build
      dockerfile: Dockerfile
    image: t3easy/typo3:8.7
